# Generated by Django 5.0.2 on 2024-04-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeepanel', '0002_alter_empdetail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
